social_auth_bitbucket.settings:
  type: config_object
  label: 'Social Auth Bitbucket settings'
  mapping:
    key:
      type: string
      label: 'Key'
    secret:
      type: string
      label: 'Secret'
    scopes:
      type: string
      label: 'Scopes to be requested'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
